#!/usr/bin/env bash
set -Eeuo pipefail

################################################################################
# functions
################################################################################
##
# usage
function usage {
  echo Usage: extact-img [URL] [DOWNLOAD_DIR]
}

# download-img
function download-img {
  local url=${1}
  local img=/var/cache/img/$(basename ${url} .xz)
  mkdir -p $(dirname ${img})
  [ ! -f ${img} ] && wget -O ${img}.xz ${url} && unxz ${img}.xz
  echo ${img}
}

##
# mount-img $path $image_dir
function mount-img {
  local img=${1}
  local img_dir=$(dirname ${img})
  local root_mnt=${img_dir}/root
  local boot_mnt=${img_dir}/boot

  mkdir -p ${root_mnt}
  mkdir -p ${boot_mnt}

  sudo kpartx -a -s ${img}
  sudo mount /dev/mapper/$(kpartx -l -v ${img} | cut -f1 -d' ' | head -n 1) ${root_mnt} > /dev/null 2>&1
  sudo mount /dev/mapper/$(kpartx -l -v ${img} | cut -f1 -d' ' | tail -n 1) ${boot_mnt} > /dev/null 2>&1

  echo "${root_mnt} ${boot_mnt}"
}

##
# unmount-img
function umount-img {
  local img=${1}
  local img_dir=$(dirname ${img})
  local root_mnt=${img_dir}/root
  local boot_mnt=${img_dir}/boot

  sudo umount ${root_mnt}
  sudo umount ${boot_mnt}
  sudo kpartx -d ${img}
}

##
# install-img
function install {
  local src=${1}
  local dst=${2}

  mkdir -p ${dst}
  rsync -a --checksum --no-devices --no-specials ${src}/ ${dst}/
}

##
# extract-img
function extract-img {
  url=${1:-"https://cdimage.ubuntu.com/releases/26.04/snapshot-4/ubuntu-26.04-snapshot4-preinstalled-server-arm64.img.xz"}
  dst=${2:-"/exports/netboot/$(basename ${url} .img.xz | cut -f1,2 -d '-')"}

  read img <<< $(download-img ${url})
  read root_mnt boot_mnt <<< $(mount-img ${img})
  trap "umount-img ${img}" EXIT 1 2 3 6

  install ${root_mnt} ${dst}
  install ${boot_mnt} ${dst}/boot
  echo ${dst}
}

################################################################################
# entrypoint
################################################################################
extract-img "$@"
