---
- name: Reload NFS exports
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: Restart tftpd-hpa
  ansible.builtin.service:
    name: tftpd-hpa
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart serve-cloud-init
  ansible.builtin.service:
    name: serve-cloud-init
    state: restarted

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
